apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- allownothing-accesspolicy.yaml
- backend-apis-ns.yaml
- backend-apis-team-workspace.yaml
- backend-apis-team-workspacesettings.yaml
- failoverpolicy.yaml
#- frontend-api-accesspolicy.yaml
#- in-namespace-accesspolicy.yaml
#- frontend-mirrorpolicy.yaml
- outlierdetectionpolicy.yaml
#- plow-loadgen-argo.yaml
- vd.yaml
- web-team-workspace.yaml
- web-team-workspacesettings.yaml
#- web-ui-extauth-policy.yaml
- web-ui-ns.yaml
- web-ui-rt-443.yaml
