# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ../../base/active/

patchesStrategicMerge:
- patches/istio-base-1.14.3.yaml
- patches/istio-ingressgateway-1.14.3.yaml
- patches/istiod-1.14.3.yaml
- patches/grafana-1.14.3.yaml
