# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- cert-manager-clusterissuer.yaml
- cert-manager-issuer.yaml
- gloo-mesh-addons.yaml
- gloo-mesh-agent-cert.yaml
- gloo-mesh-agent.yaml
- gloo-mesh-cert.yaml
- gloo-mesh-crds.yaml
- gloo-mesh-ee-helm.yaml
- gloo-mesh-relay-tls-signing-cert.yaml